config/routes.rb
Rails.application.routes.draw do

  resources :movies, except: [:new, :edit, :index]
  
  root 'movies#index'

  devise_for :users, :path => '', :path_names => { :sign_in => "login", :sign_out => "logout", :sign_up => "signup" }

  get 'new/movie', to: 'movies#new', as: 'new_movie'
  
  get 'edit/movie/:id', to: 'movies#edit', as: 'edit_movie'

end

app/models/movie.rb
class Movie < ActiveRecord::Base
	def to_param
		"#{id}-#{title}".parameterize
	end
	
	belongs_to :user
	
	validates :title, presence: true, length: {minimum: 3, maximum: 100}
	
	validates :image_url, presence: true, length: {minimum: 3, maximum: 150}
	
	validates :description, presence: true, length: {minimum: 3, maximum: 500}
	
	validates :length, presence: true, length: {minimum: 3, maximum: 10}
	
	validates :director, presence: true, length: {minimum: 3, maximum: 100}
	
	validates :rating, presence: true, numericality: { only_integer: true,
	greater_than_or_equal_to: 0, less_than_or_equal_to: 10}
	
	#{ :only_integer => true, :greater_than_or_equal_to => 0,
	#:less_than_or_equal_to => 10}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :movies
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
	before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
	before_action :set_movie, only: [:show, :edit, :update, :destroy]
	before_action :is_owner, only: [:edit, :update, :destroy]

	def index
		@movies = Movie.all.order('created_at DESC')
	end

	def show
		if request.path != movie_path(@movie)
			redirect_to @movie, status: :moved_permanently
		end
	end

	def new
		@movie = Movie.new
	end

	def edit
	end

	def create
		@movie = Movie.new(movie_params)
		@movie.user = current_user
		if @movie.save
			flash[:success] = 'Movie was successfully created.'
			redirect_to @movie
		else
			flash[:danger] = 'Could not save the movie.'
			render 'new'
		end
	end

	def update
		if @movie.update(movie_params)
			flash[:success] = "\"#{@movie.title}\" was edited."
			redirect_to @movie
		else
			flash[:danger] = "Movie was not edited."
			render 'edit'
		end
	end

	def destroy
		@movie.destroy
		flash[:success] = 'Movie was successfully deleted.'
		redirect_to root_path
	end

	private
		def set_movie
			@movie = Movie.find(params[:id])
		end

		def movie_params
			params.require(:movie).permit(:title, :description, :length, :director, :rating, :image_url)
		end
		
		def is_owner
			if current_user != @movie.user
				flash[:danger] = "You don't have the permission to do that."
				redirect_to @movie
			end
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.erb
<div class="footer text-center">
	<br><br>
	A project by Samarth Dave
	<br><br>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |key, msg| %>
	<div class="alert alert-<%= key %>" role="alert">
		<div class="container text-center">
			<strong><%= msg %></strong>
		</div>
	</div>
<% end %>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">
	<div class="container-fluid">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-1" aria-expanded="false">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<!--<a href="/" class="pull-left"><img src="/img/logo.png" height="70"></a>-->
			<%= link_to 'Movie Reviews', root_path, class: 'navbar-brand' %>
		</div>
		<div class="collapse navbar-collapse" id="navbar-collapse-1">
			<ul class="nav navbar-nav navbar-right">
				<% if !current_page?(controller: '/movies', action: 'new') && user_signed_in? %>
					<li><%= link_to 'New Movie', new_movie_path %></li>
				<% end %>
				<% if !user_signed_in? && !current_page?(controller: 'devise/sessions', action: 'new') %>
					<li><%= link_to 'Login', new_user_session_path %></li>
				<% end %>
				<% if user_signed_in? %>
					<li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
				<% end %>
			</ul>
		</div>
	</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title><%= @title ? @title : 'Movie Review' %></title>
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<%= content_tag :body, class: "#{controller_name}-#{action_name}" do %>

  <%= render 'layouts/messages' %>
  
  <%= render 'layouts/nav' %>

  <%= yield %>
  
  <%= render 'layouts/footer' %>

<% end %>
</html>

app/views/movies/_form.html.erb
<%= form_for(@movie, :html => {class: 'well'}) do |f| %>
	<% if @movie.errors.any? %>
		<div id="error_explanation">
				<h2><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h2>
			<ul>
				<% @movie.errors.full_messages.each do |message| %>
					<li><%= message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<div class="form-group">
		<%= f.label :title, class: 'sr-only' %>
		<%= f.text_field :title, class: 'form-control movies-input', placeholder: 'Title', maxlength: '100' %>
	</div>
	<div class="form-group">
		<%= f.label :image_url, class: 'sr-only' %>
		<%= f.text_field :image_url, class: 'form-control movies-input', placeholder: 'Image URL', maxlength: '150' %>
	</div>
	<div class="form-group">
		<%= f.label :description, class: 'sr-only' %>
		<%= f.text_area :description, class: 'form-control movies-input', placeholder: 'Description', maxlength: '500' %>
	</div>
	<div class="form-group">
		<%= f.label :length, class: 'sr-only' %>
		<%= f.text_field :length, class: 'form-control movies-input', placeholder: 'Length (ex. 1:50)', maxlength: '10' %>
	</div>
	<div class="form-group">
		<%= f.label :director, class: 'sr-only' %>
		<%= f.text_field :director, class: 'form-control movies-input', placeholder: 'Director', maxlength: '100' %>
	</div>
	<div class="form-group">
		<%= f.label :rating, "Rating" %>
		<% @movie.rating ? @default = @movie.rating : @default = 5 %>
		<% @array = Array.new(10) { |i| Array.new(2, (i+1)) } %>
		<%= f.select(:rating, options_for_select(@array, @default)) %>
	</div>
	<div class="form-group" style="margin: 0">
		<%= f.submit class: 'btn btn-lp' %>
	</div>
<% end %>

app/views/movies/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-4 col-md-offset-2">
			<h1>Editing Movie</h1>
			
			<%= render 'form' %>
			
			<%= link_to 'Show', @movie %> |
			<%= link_to 'Back', root_path %>
		</div>
	</div>
</div>

app/views/movies/index.html.erb
<div class="container">
	<div class="row" style="display:flex; flex-wrap: wrap;">
		<% @movies.each do |movie| %>
			<div class="col-md-3 col-sm-6">
				<div class="thumbnail">
					<%= link_to image_tag(movie.image_url, onerror: 'imgerror(this)', height: '500'), movie_path(movie) %>
				</div>
			</div>
		<% end %>
	</div>
	<br>
	<%= link_to 'New Movie', new_movie_path, class: 'btn btn-tl' %>
</div>

app/views/movies/new.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-4 col-md-offset-2">
			<h1>New Movie</h1>
	
			<%= render 'form' %>
			
			<%= link_to 'Back', root_path %>
		</div>
	</div>
</div>

app/views/movies/show.html.erb
<div class="container">
	<div class="panel panel-default">
		<div class="panel-body">
			<div class="row">
				<div class="col-sm-6 col-md-4">
					<%= image_tag(@movie.image_url, onerror: 'imgerror(this)', height: '500') %>
					<table class="table">
						<tr>
							<br><br>
							<td>Rating</td>
							<% @array = Array.new(10) { |i| Array.new(2, (i+1)) } %>
							<td><%= select_tag(:rating, options_for_select(@array, @movie.rating)) %></td>
						</tr>
						<tr>
							<td>Director</td>
							<td><%= @movie.director %></td>
						</tr>
						<tr>
							<td>Length</td>
							<td><%= @movie.length %></td>
						</tr>
						<tr>
							<td>Movie Review created by</td>
							<td><%= @movie.user.email %></td>
						</tr>
					</table>
				</div>
				<div class="col-sm-5 col-sm-offset-0 col-md-7">
					<h1><%= @movie.title %> <% if current_user == @movie.user %><%= link_to "edit", edit_movie_path(@movie), class: 'btn btn-primary btn-xs' %> <%= link_to "delete", movie_path(@movie), method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-danger btn-xs' %><% end %></h1>
					<p><%= @movie.description %></p>
				</div>
			</div>
		</div>
	</div>
</div>